# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- ci-*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - task: Docker@2
       displayName: Build Release
       condition: succeededOrFailed()
       inputs:
         containerRegistry: 'p3bankacr_connection'
         repository: 'api-release'
         command: 'build'
         Dockerfile: 'Dockerfile'
         tags: |
          $(tag)
          release
          latest
        
     - task: Docker@2
       displayName: Push Release
       inputs:
        containerRegistry: 'p3bankacr_connection'
        command: 'push'
        repository: 'api-release'
        tags: |
          $(tag)
          release
          latest
